name: dotnet-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v4
      
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Run .NET Restore
      run: dotnet restore
    
    - name: Run .NET Build
      run: dotnet build --no-restore

    - name: Run .NET Test
      run: dotnet test --no-build

    - name: Publish
      run: dotnet publish -c Release -r win-64x -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ./publish
